export const endpoints = {
  auth: {
    login: '/auth/login',
    me: '/auth/me',
    logout: '/auth/logout',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
  },
  products: {
    root: '/products',
    options: '/products/options',
    catalog: '/products/catalog',
    categories: '/products/categories',
    brands: '/products/brands',
    units: '/products/units',
    category: (id: string) => `/products/categories/${id}`,
    categoryStatus: (id: string) => `/products/categories/${id}/status`,
    brand: (id: string) => `/products/brands/${id}`,
    brandStatus: (id: string) => `/products/brands/${id}/status`,
    unit: (id: string) => `/products/units/${id}`,
    unitStatus: (id: string) => `/products/units/${id}/status`,
    detail: (id: string) => `/products/${id}`,
    status: (id: string) => `/products/${id}/status`,
  },
  inventory: {
    root: '/inventory',
    existence: '/inventory/existencia',
    movements: '/inventory/historial',
    initialStock: '/inventory/stock-inicial',
    entries: '/inventory/entradas',
    exits: '/inventory/salidas',
    adjustments: '/inventory/ajustes',
  },
  services: {
    root: '/services',
    options: '/services/options',
    detail: (id: string) => `/services/${id}`,
    status: (id: string) => `/services/${id}/status`,
  },
  purchases: '/purchases',
  sales: {
    root: '/sales',
    catalog: '/sales/catalogo',
    detail: (id: string) => `/sales/${id}`,
    confirm: (id: string) => `/sales/${id}/confirm`,
  },
  appointments: {
    root: '/appointments',
    detail: (id: string) => `/appointments/${id}`,
    reschedule: (id: string) => `/appointments/${id}/reschedule`,
    cancel: (id: string) => `/appointments/${id}/cancel`,
  },
  customers: {
    root: '/customers',
    detail: (id: string) => `/customers/${id}`,
  },
  vehicles: {
    root: '/vehicles',
    detail: (id: string) => `/vehicles/${id}`,
  },
  cash: '/cash',
  users: {
    root: '/users',
    roles: '/users/roles',
    detail: (id: string) => `/users/${id}`,
    role: (id: string) => `/users/${id}/role`,
    status: (id: string) => `/users/${id}/status`,
  },
  notifications: '/notifications',
  profile: '/profile',
  reports: '/reports',
  barcodes: '/barcodes',
  dashboard: '/dashboard',
} as const
