export const endpoints = {
  auth: {
    login: '/auth/login',
    me: '/auth/me',
    logout: '/auth/logout',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
  },
  products: {
    root: '/products',
    options: '/products/options',
    categories: '/products/categories',
    brands: '/products/brands',
    units: '/products/units',
    detail: (id: string) => `/products/${id}`,
    status: (id: string) => `/products/${id}/status`,
  },
  inventory: '/inventory',
  purchases: '/purchases',
  sales: '/sales',
  customers: '/customers',
  cash: '/cash',
  users: '/users',
  notifications: '/notifications',
  profile: '/profile',
  reports: '/reports',
  barcodes: '/barcodes',
  dashboard: '/dashboard',
} as const
