-- AlterEnum
ALTER TYPE "AuditEventType" ADD VALUE 'WORK_ORDER_EXECUTION_STARTED';

-- AlterEnum
ALTER TYPE "AuditEventType" ADD VALUE 'WORK_ORDER_ACTIVITY_CREATED';

-- AlterEnum
ALTER TYPE "AuditEventType" ADD VALUE 'WORK_ORDER_ACTIVITY_COMPLETED';

-- AlterEnum
ALTER TYPE "AuditEventType" ADD VALUE 'WORK_ORDER_PRODUCT_CONSUMED';

-- AlterEnum
ALTER TYPE "AuditEventType" ADD VALUE 'WORK_ORDER_PRODUCT_RETURNED';

-- AlterEnum
ALTER TYPE "AuditEventType" ADD VALUE 'WORK_ORDER_READY_FOR_DELIVERY';

-- AlterEnum
ALTER TYPE "AuditEventType" ADD VALUE 'WORK_ORDER_DELIVERED';