-- AlterEnum
ALTER TYPE "AuditEventType" ADD VALUE 'SERVICE_CREATED';
ALTER TYPE "AuditEventType" ADD VALUE 'SERVICE_UPDATED';
ALTER TYPE "AuditEventType" ADD VALUE 'SERVICE_DEACTIVATED';
ALTER TYPE "AuditEventType" ADD VALUE 'SERVICE_ACTIVATED';
ALTER TYPE "AuditEventType" ADD VALUE 'INVENTORY_STOCK_INITIALIZED';
ALTER TYPE "AuditEventType" ADD VALUE 'INVENTORY_ENTRY_REGISTERED';
ALTER TYPE "AuditEventType" ADD VALUE 'INVENTORY_EXIT_REGISTERED';
ALTER TYPE "AuditEventType" ADD VALUE 'INVENTORY_ADJUSTMENT_REGISTERED';