export const paths = {
  login: '/login',
  forgotPassword: '/recuperar-contrasena',
  resetPassword: '/restablecer-contrasena',
  dashboard: '/dashboard',
  products: '/productos',
  barcodes: '/codigos-de-barras',
  inventory: '/inventario',
  purchases: '/compras',
  sales: '/ventas',
  customers: '/clientes',
  customerDetail: '/clientes/:id',
  vehicles: '/vehiculos',
  vehicleDetail: '/vehiculos/:id',
  cash: '/caja',
  users: '/usuarios',
  notifications: '/notificaciones',
  profile: '/perfil',
  reports: '/reportes',
} as const
