-- AlterEnum
ALTER TYPE "AuditEventType" ADD VALUE 'APPOINTMENT_ATTENDED';

-- AlterEnum
ALTER TYPE "AuditEventType" ADD VALUE 'WORK_ORDER_CREATED';

-- AlterEnum
ALTER TYPE "AuditEventType" ADD VALUE 'WORK_ORDER_DIAGNOSIS_UPDATED';

-- AlterEnum
ALTER TYPE "AuditEventType" ADD VALUE 'WORK_ORDER_BUDGET_SAVED';

-- AlterEnum
ALTER TYPE "AuditEventType" ADD VALUE 'WORK_ORDER_BUDGET_SENT';

-- AlterEnum
ALTER TYPE "AuditEventType" ADD VALUE 'WORK_ORDER_BUDGET_APPROVED';

-- AlterEnum
ALTER TYPE "AuditEventType" ADD VALUE 'WORK_ORDER_BUDGET_REJECTED';

-- AlterEnum
ALTER TYPE "AuditEventType" ADD VALUE 'WORK_ORDER_TECHNICIAN_ASSIGNED';