-- AlterEnum
ALTER TYPE "AuditEventType" ADD VALUE 'PRODUCT_CREATED';
ALTER TYPE "AuditEventType" ADD VALUE 'PRODUCT_UPDATED';
ALTER TYPE "AuditEventType" ADD VALUE 'PRODUCT_DEACTIVATED';
ALTER TYPE "AuditEventType" ADD VALUE 'PRODUCT_ACTIVATED';