-- AlterEnum
ALTER TYPE "AuditEventType" ADD VALUE 'APPOINTMENT_CREATED';
ALTER TYPE "AuditEventType" ADD VALUE 'APPOINTMENT_RESCHEDULED';
ALTER TYPE "AuditEventType" ADD VALUE 'APPOINTMENT_CANCELLED';