-- AlterEnum
ALTER TYPE "AuditEventType" ADD VALUE 'USER_CREATED';
ALTER TYPE "AuditEventType" ADD VALUE 'USER_UPDATED';
ALTER TYPE "AuditEventType" ADD VALUE 'USER_ROLE_CHANGED';
ALTER TYPE "AuditEventType" ADD VALUE 'USER_DEACTIVATED';
ALTER TYPE "AuditEventType" ADD VALUE 'USER_ACTIVATED';